// ----------------------------------------------------------------------------
// 'SDeltaPtCutStudy.h'
// Derek Anderson
// 06.29.2023
//
// Reads in the 'ntp_track' Ntuple
// generated by the SVtxEvaluator
// class and studies how deltapt/pt
// varies with quality cuts.
// ----------------------------------------------------------------------------

#ifndef SDELTAPTCUTSTUDY_H
#define SDELTAPTCUTSTUDY_H

// standard c includes
#include <cmath>
#include <vector>
#include <cassert>
#include <cstdlib>
#include <utility>
#include <iostream>
// root includes
#include "TH1.h"
#include "TH2.h"
#include "TPad.h"
#include "TFile.h"
#include "TMath.h"
#include "TError.h"
#include "TNtuple.h"
#include "TString.h"
#include "TLegend.h"
#include "TCanvas.h"
#include "TPaveText.h"
#include "TDirectory.h"

using namespace std;

// global constants
/* will go here */



class SDeltaPtCutStudy {

  public:

    // ctor/dtor
    SDeltaPtCutStudy();
    ~SDeltaPtCutStudy();

    // public methods
    void Init();
    void Analyze();
    void End();

  private:

    /* stuff will go here */

};  // end SDeltaPtCutStudy definition

#endif

// end ------------------------------------------------------------------------
