// ----------------------------------------------------------------------------
// 'SDeltaPtCutStudy.cc'
// Derek Anderson
// 06.29.2023
//
// Reads in the 'ntp_track' Ntuple
// generated by the SVtxEvaluator
// class and studies how deltapt/pt
// varies with quality cuts.
// ----------------------------------------------------------------------------

#define SDELTAPTCUTSTUDY_CC

// header files
#include "SDeltaPtCutStudy.h"

using namespace std;



// ctor/dtor ------------------------------------------------------------------

SDeltaPtCutStudy::SDeltaPtCutStudy() {

  /* stuff will go here */

}  // end ctor




SDeltaPtCutStudy::~SDeltaPtCutStudy() {

  /* stuff will go here */

}  // end dtor



//  main methods --------------------------------------------------------------

void SDeltaPtCutStudy::Init() {

  /* stuff will go here */
  return;

}  // end Init()



void SDeltaPtCutStudy::Analyze() {

  /* stuff will go here */
  return;

}  // end Analyze()



void SDeltaPtCutStudy::End() {

  /* stuff will go here */
  return ;

}  // end End()

// end ------------------------------------------------------------------------
